name: Build STM32 Firmware

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install ARM GCC Toolchain
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc-arm-none-eabi binutils-arm-none-eabi

      - name: Build firmware
        run: |
          make

      - name: Upload firmware binary
        uses: actions/upload-artifact@v3
        with:
          name: firmware-bin
          path: "**/*.bin"
