#include "stm32h7xx_hal.h"
#include "motor_control.h"

// Note: SystemClock_Config should be generated by CubeMX in the client's project.
// Here it's declared so the client's build will link with their CubeMX SystemClock_Config.
void SystemClock_Config(void);

int main(void)
{
    HAL_Init();
    SystemClock_Config(); // client will provide this from CubeMX

    Motor_Init();

    while (1)
    {
        Motor_Set(1);
        HAL_Delay(100); // 100 ms on
        Motor_Set(0);
        HAL_Delay(100); // 100 ms off
    }
}
